---
mqtt:
  broker: localhost
  port: 1883
pump:
  pin: 7
  delay: 5
zones:
  - zone: Front Yard
    pin: 0
  - zone: Backyard
    pin: 1
plans:
  - name: Morning Watering
    zone_durations:
      - zone: Front Yard
        duration: 30
      - zone: Backyard
        duration: 45
  - name: Evening Watering
    zone_durations:
      - zone: Front Yard
        duration: 20
      - zone: Backyard
        duration: 35
